name: Gen Issue

on:
  schedule:
    - cron: '0 0 1 FEB *'
    - cron: '0 0 1 MAY *'
    - cron: '0 0 1 AUG *'
    - cron: '0 0 1 NOV *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: gen issue
    steps:
      - uses: actions/checkout@v3

      - name: Today's date
        run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - uses: imjohnbo/issue-bot@v3
        with:
          assignees: "yasudanaoya"
          title: 職務経歴書を更新しましょう ${{ env.TODAY }}
          body: |-
            - [ ] docs/README.md の更新

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
