name: Gen Issue

on:
  schedule:
    - cron: '0 0 1 FEB *'
    - cron: '0 0 1 MAY *'
    - cron: '0 0 1 AUG *'
    - cron: '0 0 1 NOV *'

jobs:
  build:
    runs-on: ubuntu-latest

    name: gen issue
    steps:
      - uses: actions/checkout@v3

      - uses: imjohnbo/issue-bot@3
        with:
          assignees: "yasudanaoya"
          title: 職務経歴書を更新しましょう {{ date | date('YYYY/MM/DD') }}
          body: |
            - [ ] docs/README.md の更新
            - [ ] release をする
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
